project:
  type: website
  output-dir: docs

website:
  title: "Assignment 5"
  navbar:
   left:
    - href: index.qmd
      text: Home
    - href: cv.qmd
      text: CV
    - href: contact.qmd
      text: Contact Information
    - href: posts.qmd
      text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

