---
title: "Curriculum Vitae"
---

# Name
Gia Bach Pham

# Contact Information

Phone number: 204 996 6696

Email: phamgiabach0609@gmail.com

# Education
Bachelor of Business Administration - Accounting

# Current Position
Proctor and Tutor at University of Winnipeg   (Sept 2023 - present)

Description: 

- Provide tutoring to students, which may include explaining and demonstrating concepts and
procedures, and clarifying subject areas.
- Maintaining regularly scheduled and posted times to provide consultation and feedback to
students on coursework, quality of materials submitted for grading, and other similar matters.
- Maintaining records; may assist in the reproduction of tests; organize course materials; etc.
- Assist with proctoring/invigilating tests, exams and quizzes.

# Previous Position

Summer Intern   (May 2024 - August 2024)

Description:

- Have the understanding and independent use of Excel, Outlook, Access database tools,
electronic file management and professional email templates.
- Be comfortable when working independently as well as in a team environment, always be
supportive and ready to contribute to achieve departmental goals.
- Maintaining professional communication with the CSS (Customer Service Specialist) to
understand clients’ needs and require additional information when needed.
- Processing members’ applications, individual and bulk contributions in a monthly routine
with high level of accuracy.
- Counting members and preparing certified financial statements for Canada Life’s clients at
year end.
- Sorting and reporting terminated members to leaders in order to keep records.
- Efficient in job rotation and ensure smooth transitions when being moved between different
